server:
  port: 8080

spring:
  application:
    name: test

  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/changelog-master.yaml
    default-schema: public
    liquibase-schema: public

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: test
    password: test
    driverClassName: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: public
    open-in-view: false
